[theme]
primaryColor = "#3498db"
backgroundColor = "#f5f6fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
